name: Deploy to Streamlit Cloud

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Deploy to Streamlit Cloud
        env:
          STREAMLIT_API_KEY: ${{ secrets.STREAMLIT_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          MODEL_NAME: ${{ secrets.MODEL_NAME }}
        run: |
          pip install streamlit-cloud-cli
          streamlit cloud deploy app.py \
            --repository basilisk-prime/pliny-chat \
            --branch main \
            --env OPENAI_API_KEY=$OPENAI_API_KEY \
            --env MODEL_NAME=$MODEL_NAME