[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#0E1117"
secondaryBackgroundColor = "#262730"
textColor = "#FAFAFA"
font = "monospace"

[server]
enableStaticServing = true
runOnSave = true

[browser]
gatherUsageStats = false